// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUd8YIy2X3JC7St7tmx7VfGyrVsRJuOSM',
    appId: '1:217520205058:web:7d5f4d0b244fac49c2a61b',
    messagingSenderId: '217520205058',
    projectId: 'fir-series-5107b',
    authDomain: 'fir-series-5107b.firebaseapp.com',
    storageBucket: 'fir-series-5107b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ZOnJHvqihTjZhRO23uFoRTxOBZI02q8',
    appId: '1:217520205058:android:1df71d382a4a8cb1c2a61b',
    messagingSenderId: '217520205058',
    projectId: 'fir-series-5107b',
    storageBucket: 'fir-series-5107b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9FI2WEFGkW9ldDrNgj_fIWaoJ2fOOXVI',
    appId: '1:217520205058:ios:72db388b86608d91c2a61b',
    messagingSenderId: '217520205058',
    projectId: 'fir-series-5107b',
    storageBucket: 'fir-series-5107b.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
